### PR TITLE
Zennamo/flux rw reworking

### PR DESCRIPTION
**Pull request by twongjirad**
Joseph fixed the flux weight calculator. Will allow us to properly weight neutrino events.

### CODE REVIEW

**Comment by twongjirad** [comment]
@jzennamo does the last commit have the flux files needed to do the reweighting? how big are they?
@drinkingkazu do we want these root files in the repository? or do we want to have the user download them separately.

**Comment by drinkingkazu** [comment]
The decision depends on the size and frequency-of-update IMO. Let's wait to see a reply.

**Comment by jzennamo** [comment]
I have not pushed the needed root files. These currently live here:

/grid/fermiapp/products/uboone/uboone_data/v01_14_00/uboonebeam/bnb_gsimple/bnb_gsimple_fluxes_02.28.2014_470_rwhist/

They shouldn’t need updating unless there are bugs discovered (hence why they are being updated now). Also the central value file is only 13 kb while the corrected file is 38 kb. 

Let me know if you need anymore info or if you want me to push them into the repo.

**Comment by drinkingkazu** [comment]
Thanks! that sounds like there's no problem to push into the repo IMO.

**Comment by jzennamo** [comment]
Done! Enjoy!

**Pull request merged**
