### PR TITLE
add mceventweights

### PR DESCRIPTION
**Pull request by mastbaum**
Add a container for larsoft `evwgh::MCEventWeight` products, in `larlite::mceventweight`

/cc @drinkingkazu

### CODE REVIEW

**Comment by drinkingkazu** [comment]
@mastbaum if I build this w/ larsoft v06_20_00 is that ok? This just sets ROOT version and I'm sure it's same version for today's larsoft develop branch...

Once you confirmed I'll build, distribute UPS.

**Comment by mastbaum** [comment]
Sounds good, thank you!

**Comment by drinkingkazu** [comment]
done!
[uboone@uboonegpvm04 uboone]$ ups list -aK+ larlite | grep current
"larlite" "v06_20_00" "Linux64bit+2.6-2.12" "e10:prof" "current"

**Comment by mastbaum** [comment]
Great, thanks again!

**Pull request merged**
