### PR TITLE
Update table file.

### PR DESCRIPTION
**Pull request by hgreenlee**
Update table file to support qualifiers and e14.

### CODE REVIEW

**Comment by twongjirad** [comment]
@hgreenlee, you would like a tag for this commit, right? Replace the last one?

**Comment by hgreenlee** [comment]
Hello Taritree,

Yes, move the tag v06_26_01_01, or make a new one.

Herb

**Comment by twongjirad** [comment]
Will do!

**Comment by twongjirad** [comment]
Updated tag v06_26_01_01

**Pull request merged**
